package com.personal.demo.hello.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2012-10-09T19:59:53.300+01:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(targetNamespace = "http://hello.demo.personal.com/", name = "HelloWorld")
public interface HelloWorld {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://hello.demo.personal.com/", className = "com.personal.demo.hello.SayHello")
    @WebMethod
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://hello.demo.personal.com/", className = "com.personal.demo.hello.SayHelloResponse")
    public java.lang.String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
